### ISSUE TITLE
remove  if layer % 12 == 0: and use AdafactorOptimizer can train all 432 vars

### ISSUE THREAD

**Issue by deepbluesea** [jkraybill/gpt-2-b#1]
https://github.com/deepbluesea/gpt-2
https://github.com/deepbluesea/gpt-2/blob/finetuning/train.py
https://github.com/deepbluesea/gpt-2/blob/finetuning/src/model.py

example

!PYTHONPATH=src python ./train.py --dataset aqxx.txt --model_name 774M --batch_size 1 --learning_rate 0.0003 --memory_saving_gradients --only_train_transformer_layers --optimizer b --save_every 10000 --sample_every 50 --sample_length 1023 --train_vars_limit --train_vars 432

t4 == 432
k80 == 408

-Basedblue

**Comment by epetros** [comment]
> 
> 
> https://github.com/deepbluesea/gpt-2
> https://github.com/deepbluesea/gpt-2/blob/finetuning/train.py
> https://github.com/deepbluesea/gpt-2/blob/finetuning/src/model.py
> 
> example
> 
> !PYTHONPATH=src python ./train.py --dataset aqxx.txt --model_name 774M --batch_size 1 --learning_rate 0.0003 --memory_saving_gradients --only_train_transformer_layers --optimizer b --save_every 10000 --sample_every 50 --sample_length 1023 --train_vars_limit --train_vars 432
> 
> t4 == 432
> k80 == 408
> 
> -Basedblue

I am getting the following error while trying the above suggestion:
Traceback (most recent call last):
  File "./train.py", line 14, in <module>
    import model, sample, encoder
  File "/content/gpt-2/src/model.py", line 3, in <module>
    from tensorflow.contrib.training import HParams
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/__init__.py", line 37, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 38, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/rnn/__init__.py", line 91, in <module>
    from tensorflow.contrib.rnn.python.ops.lstm_ops import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py", line 298, in <module>
    @ops.RegisterGradient("BlockLSTM")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 2489, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/registry.py", line 61, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/registry.py:66)"

**Comment by deepbluesea** [comment]
downgrade tensorflow to 1.14.0

!pip install tensorflow==1.14.0
!pip install tensorflow-gpu==1.14.0

also if using my repo remember to run this before training

import os
os.environ['TF_AUTO_MIXED_PRECISION_GRAPH_REWRITE_IGNORE_PERFORMANCE'] = '1'

**Comment by epetros** [comment]
> 
> 
> downgrade tensorflow to 1.14.0
> 
> !pip install tensorflow==1.14.0
> !pip install tensorflow-gpu==1.14.0
> 
> also if using my repo remember to run this before training
> 
> import os
> os.environ['TF_AUTO_MIXED_PRECISION_GRAPH_REWRITE_IGNORE_PERFORMANCE'] = '1'

It is working, thanks!
